// アカウントGoogleTokenリフレッシュリクエスト

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file account/account_refresh_google_token_request.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message api.admin.AccountRefreshGoogleTokenRequest
 */
export class AccountRefreshGoogleTokenRequest extends Message<AccountRefreshGoogleTokenRequest> {
  constructor(data?: PartialMessage<AccountRefreshGoogleTokenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.admin.AccountRefreshGoogleTokenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): AccountRefreshGoogleTokenRequest {
    return new AccountRefreshGoogleTokenRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): AccountRefreshGoogleTokenRequest {
    return new AccountRefreshGoogleTokenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): AccountRefreshGoogleTokenRequest {
    return new AccountRefreshGoogleTokenRequest().fromJsonString(
      jsonString,
      options
    );
  }

  static equals(
    a:
      | AccountRefreshGoogleTokenRequest
      | PlainMessage<AccountRefreshGoogleTokenRequest>
      | undefined,
    b:
      | AccountRefreshGoogleTokenRequest
      | PlainMessage<AccountRefreshGoogleTokenRequest>
      | undefined
  ): boolean {
    return proto3.util.equals(AccountRefreshGoogleTokenRequest, a, b);
  }
}
