// アカウント

// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file account/account_handler.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AccountGetGoogleLoginUrlRequest } from "./account_get_google_login_url_request_pb.js";
import { AccountGetGoogleLoginUrlResponse } from "./account_get_google_login_url_response_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { AccountGetGoogleLoginTokenRequest } from "./account_get_google_login_token_request_pb.js";
import { AccountGetGoogleLoginTokenResponse } from "./account_get_google_login_token_response_pb.js";

/**
 * @generated from service api.admin.Account
 */
export const Account = {
  typeName: "api.admin.Account",
  methods: {
    /**
     * @generated from rpc api.admin.Account.GetGoogleLoginUrl
     */
    getGoogleLoginUrl: {
      name: "GetGoogleLoginUrl",
      I: AccountGetGoogleLoginUrlRequest,
      O: AccountGetGoogleLoginUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc api.admin.Account.GetGoogleLoginToken
     */
    getGoogleLoginToken: {
      name: "GetGoogleLoginToken",
      I: AccountGetGoogleLoginTokenRequest,
      O: AccountGetGoogleLoginTokenResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
