// アカウントGoogleToken情報取得リクエスト

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file account/account_get_google_token_info_request.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message api.admin.AccountGetGoogleTokenInfoRequest
 */
export class AccountGetGoogleTokenInfoRequest extends Message<AccountGetGoogleTokenInfoRequest> {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken = "";

  constructor(data?: PartialMessage<AccountGetGoogleTokenInfoRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.admin.AccountGetGoogleTokenInfoRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: "access_token",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): AccountGetGoogleTokenInfoRequest {
    return new AccountGetGoogleTokenInfoRequest().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): AccountGetGoogleTokenInfoRequest {
    return new AccountGetGoogleTokenInfoRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): AccountGetGoogleTokenInfoRequest {
    return new AccountGetGoogleTokenInfoRequest().fromJsonString(
      jsonString,
      options
    );
  }

  static equals(
    a:
      | AccountGetGoogleTokenInfoRequest
      | PlainMessage<AccountGetGoogleTokenInfoRequest>
      | undefined,
    b:
      | AccountGetGoogleTokenInfoRequest
      | PlainMessage<AccountGetGoogleTokenInfoRequest>
      | undefined
  ): boolean {
    return proto3.util.equals(AccountGetGoogleTokenInfoRequest, a, b);
  }
}
