// アカウントGoogleログインToken取得レスポンス

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file account/account_get_google_login_token_response.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { AdminAccountGoogleToken } from "./adminAccountGoogleToken/admin_account_google_token_pb.js";

/**
 * @generated from message api.admin.AccountGetGoogleLoginTokenResponse
 */
export class AccountGetGoogleLoginTokenResponse extends Message<AccountGetGoogleLoginTokenResponse> {
  /**
   * @generated from field: optional api.admin.AdminAccountGoogleToken admin_account_google_token = 1;
   */
  adminAccountGoogleToken?: AdminAccountGoogleToken;

  constructor(data?: PartialMessage<AccountGetGoogleLoginTokenResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.admin.AccountGetGoogleLoginTokenResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    {
      no: 1,
      name: "admin_account_google_token",
      kind: "message",
      T: AdminAccountGoogleToken,
      opt: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): AccountGetGoogleLoginTokenResponse {
    return new AccountGetGoogleLoginTokenResponse().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): AccountGetGoogleLoginTokenResponse {
    return new AccountGetGoogleLoginTokenResponse().fromJson(
      jsonValue,
      options
    );
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): AccountGetGoogleLoginTokenResponse {
    return new AccountGetGoogleLoginTokenResponse().fromJsonString(
      jsonString,
      options
    );
  }

  static equals(
    a:
      | AccountGetGoogleLoginTokenResponse
      | PlainMessage<AccountGetGoogleLoginTokenResponse>
      | undefined,
    b:
      | AccountGetGoogleLoginTokenResponse
      | PlainMessage<AccountGetGoogleLoginTokenResponse>
      | undefined
  ): boolean {
    return proto3.util.equals(AccountGetGoogleLoginTokenResponse, a, b);
  }
}
