name: UserExchangeItem
package: userExchangeItem
comment: "ユーザー交換アイテム"

structure:
  UserId:
    name: user_id
    type: string
    nullable: false
    number: 1
    comment: "ユーザーID"
  MasterExchangeItemId:
    name: master_exchange_item_id
    type: int64
    nullable: false
    number: 2
    comment: "交換アイテムID"
  Count:
    name: count
    type: int32
    nullable: false
    number: 3
    comment: "残りのアイテム数"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 4
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 5
    comment: "更新日時"
primary:
  - UserId,MasterExchangeItemId
unique:
  - UserId,MasterExchangeItemId
