version: '3.8'

name: gc-server-api

volumes:
  mysql-local:
    driver: local
  redis-local:
    driver: local

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./platform/docker/mysql/conf.d:/etc/mysql/conf.d
      - ./platform/docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-local:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - ./platform/docker/redis/redis.conf:/etc/redis.conf
      - redis-local:/data
    tty: true

  gen:
    env_file:
      - .env.local
    build:
      target: prod
      context: .
      dockerfile: ./platform/docker/gen/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      - mysql
      - redis

  api-game:
    env_file:
      - .env.local
    build:
      target: prod
      context: .
      dockerfile: ./platform/docker/api/game/Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - "50051:50051"
    tty: true
    depends_on:
      - mysql
      - redis
