name: CommonHealth
package: CommonHealth
comment: "ヘルスチェック"

structure:
  HealthId:
    name: health_id
    type: int64
    nullable: false
    number: 1
    comment: "ヘルスID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "アクション名"
  CommonHealthType:
    name: common_health_type
    type: enum
    package: health/commonHealth
    nullable: false
    number: 3
    comment: "ヘルスチェックタイプ"
primary:
  - HealthId
unique:
  - HealthId
