// ヘルスチェック

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file health/masterHealth/master_health.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { MasterHealthEnum } from "./master_health_enum_pb.js";

/**
 * @generated from message api.admin.MasterHealth
 */
export class MasterHealth extends Message<MasterHealth> {
  /**
   * @generated from field: int64 health_id = 1;
   */
  healthId = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: api.admin.MasterHealthEnum master_health_enum = 3;
   */
  masterHealthEnum = MasterHealthEnum.MasterNone;

  constructor(data?: PartialMessage<MasterHealth>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.admin.MasterHealth";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "health_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    {
      no: 3,
      name: "master_health_enum",
      kind: "enum",
      T: proto3.getEnumType(MasterHealthEnum),
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): MasterHealth {
    return new MasterHealth().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): MasterHealth {
    return new MasterHealth().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): MasterHealth {
    return new MasterHealth().fromJsonString(jsonString, options);
  }

  static equals(
    a: MasterHealth | PlainMessage<MasterHealth> | undefined,
    b: MasterHealth | PlainMessage<MasterHealth> | undefined
  ): boolean {
    return proto3.util.equals(MasterHealth, a, b);
  }
}
