// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file health/masterHealth/master_health_enum.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum api.admin.MasterHealthEnum
 */
export enum MasterHealthEnum {
  /**
   * @generated from enum value: MasterNone = 0;
   */
  MasterNone = 0,

  /**
   * @generated from enum value: MasterSuccess = 1;
   */
  MasterSuccess = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(MasterHealthEnum)
proto3.util.setEnumType(MasterHealthEnum, "api.admin.MasterHealthEnum", [
  { no: 0, name: "MasterNone" },
  { no: 1, name: "MasterSuccess" },
]);
