// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/game-core/gc-server/api/admin/presentation/handler/health"
	"github.com/game-core/gc-server/api/admin/presentation/interceptor/auth"
	health2 "github.com/game-core/gc-server/api/admin/usecase/health"
	"github.com/game-core/gc-server/config/database"
	"github.com/game-core/gc-server/config/logger"
	"github.com/game-core/gc-server/pkg/domain/model/account"
	"github.com/game-core/gc-server/pkg/domain/model/action"
	"github.com/game-core/gc-server/pkg/domain/model/event"
	"github.com/game-core/gc-server/pkg/domain/model/exchange"
	health3 "github.com/game-core/gc-server/pkg/domain/model/health"
	"github.com/game-core/gc-server/pkg/domain/model/item"
	"github.com/game-core/gc-server/pkg/domain/model/loginBonus"
	"github.com/game-core/gc-server/pkg/domain/model/profile"
	"github.com/game-core/gc-server/pkg/domain/model/shard"
	"github.com/game-core/gc-server/pkg/domain/model/transaction"
	userItemBox2 "github.com/game-core/gc-server/pkg/infrastructure/cloudwatch/user/userItemBox"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/admin/adminHealth"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/common/commonHealth"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/common/commonTransaction"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterAction"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterActionRun"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterActionStep"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterActionTrigger"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterEvent"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterExchange"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterExchangeCost"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterExchangeItem"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterHealth"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterItem"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterLoginBonus"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterLoginBonusItem"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterLoginBonusSchedule"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterShard"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/master/masterTransaction"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userAccount"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userAction"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userExchange"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userExchangeItem"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userItemBox"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userLoginBonus"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userProfile"
	"github.com/game-core/gc-server/pkg/infrastructure/mysql/user/userTransaction"
	userAccount2 "github.com/game-core/gc-server/pkg/infrastructure/redis/user/userAccount"
	"github.com/game-core/gc-server/pkg/infrastructure/redis/user/userAccountToken"
	masterTransaction2 "github.com/game-core/gc-server/pkg/infrastructure/redis/user/userTransaction"
)

// Injectors from wire.go:

func InitializeAuthInterceptor() auth.AuthInterceptor {
	accountService := InitializeAccountService()
	authInterceptor := auth.NewAuthInterceptor(accountService)
	return authInterceptor
}

func InitializeHealthHandler() health.HealthHandler {
	healthUsecase := InitializeHealthUsecase()
	healthHandler := health.NewHealthHandler(healthUsecase)
	return healthHandler
}

func InitializeHealthUsecase() health2.HealthUsecase {
	healthService := InitializeHealthService()
	healthUsecase := health2.NewHealthUsecase(healthService)
	return healthUsecase
}

func InitializeAccountService() account.AccountService {
	shardService := InitializeShardService()
	mysqlHandler := database.NewMysql()
	userAccountMysqlRepository := userAccount.NewUserAccountDao(mysqlHandler)
	redisHandler := database.NewRedis()
	userAccountRedisRepository := userAccount2.NewUserAccountDao(redisHandler)
	userAccountTokenRedisRepository := userAccountToken.NewUserAccountTokenDao(redisHandler)
	accountService := account.NewAccountService(shardService, userAccountMysqlRepository, userAccountRedisRepository, userAccountTokenRedisRepository)
	return accountService
}

func InitializeActionService() action.ActionService {
	mysqlHandler := database.NewMysql()
	masterActionMysqlRepository := masterAction.NewMasterActionDao(mysqlHandler)
	masterActionRunMysqlRepository := masterActionRun.NewMasterActionRunDao(mysqlHandler)
	masterActionStepMysqlRepository := masterActionStep.NewMasterActionStepDao(mysqlHandler)
	masterActionTriggerMysqlRepository := masterActionTrigger.NewMasterActionTriggerDao(mysqlHandler)
	userActionMysqlRepository := userAction.NewUserActionDao(mysqlHandler)
	actionService := action.NewActionService(masterActionMysqlRepository, masterActionRunMysqlRepository, masterActionStepMysqlRepository, masterActionTriggerMysqlRepository, userActionMysqlRepository)
	return actionService
}

func InitializeEventService() event.EventService {
	mysqlHandler := database.NewMysql()
	masterEventMysqlRepository := masterEvent.NewMasterEventDao(mysqlHandler)
	eventService := event.NewEventService(masterEventMysqlRepository)
	return eventService
}

func InitializeExchangeService() exchange.ExchangeService {
	itemService := InitializeItemService()
	eventService := InitializeEventService()
	mysqlHandler := database.NewMysql()
	masterExchangeMysqlRepository := masterExchange.NewMasterExchangeDao(mysqlHandler)
	masterExchangeCostMysqlRepository := masterExchangeCost.NewMasterExchangeCostDao(mysqlHandler)
	masterExchangeItemMysqlRepository := masterExchangeItem.NewMasterExchangeItemDao(mysqlHandler)
	userExchangeMysqlRepository := userExchange.NewUserExchangeDao(mysqlHandler)
	userExchangeItemMysqlRepository := userExchangeItem.NewUserExchangeItemDao(mysqlHandler)
	exchangeService := exchange.NewExchangeService(itemService, eventService, masterExchangeMysqlRepository, masterExchangeCostMysqlRepository, masterExchangeItemMysqlRepository, userExchangeMysqlRepository, userExchangeItemMysqlRepository)
	return exchangeService
}

func InitializeHealthService() health3.HealthService {
	mysqlHandler := database.NewMysql()
	adminHealthMysqlRepository := adminHealth.NewAdminHealthDao(mysqlHandler)
	commonHealthMysqlRepository := commonHealth.NewCommonHealthDao(mysqlHandler)
	masterHealthMysqlRepository := masterHealth.NewMasterHealthDao(mysqlHandler)
	healthService := health3.NewHealthService(adminHealthMysqlRepository, commonHealthMysqlRepository, masterHealthMysqlRepository)
	return healthService
}

func InitializeItemService() item.ItemService {
	mysqlHandler := database.NewMysql()
	userItemBoxMysqlRepository := userItemBox.NewUserItemBoxDao(mysqlHandler)
	cloudWatchHandler := logger.NewCloudWatch()
	userItemBoxCloudWatchRepository := userItemBox2.NewUserItemBoxDao(cloudWatchHandler)
	masterItemMysqlRepository := masterItem.NewMasterItemDao(mysqlHandler)
	itemService := item.NewItemService(userItemBoxMysqlRepository, userItemBoxCloudWatchRepository, masterItemMysqlRepository)
	return itemService
}

func InitializeLoginBonusService() loginBonus.LoginBonusService {
	itemService := InitializeItemService()
	eventService := InitializeEventService()
	mysqlHandler := database.NewMysql()
	userLoginBonusMysqlRepository := userLoginBonus.NewUserLoginBonusDao(mysqlHandler)
	masterLoginBonusMysqlRepository := masterLoginBonus.NewMasterLoginBonusDao(mysqlHandler)
	masterLoginBonusItemMysqlRepository := masterLoginBonusItem.NewMasterLoginBonusItemDao(mysqlHandler)
	masterLoginBonusScheduleMysqlRepository := masterLoginBonusSchedule.NewMasterLoginBonusScheduleDao(mysqlHandler)
	loginBonusService := loginBonus.NewLoginBonusService(itemService, eventService, userLoginBonusMysqlRepository, masterLoginBonusMysqlRepository, masterLoginBonusItemMysqlRepository, masterLoginBonusScheduleMysqlRepository)
	return loginBonusService
}

func InitializeProfileService() profile.ProfileService {
	mysqlHandler := database.NewMysql()
	userProfileMysqlRepository := userProfile.NewUserProfileDao(mysqlHandler)
	profileService := profile.NewProfileService(userProfileMysqlRepository)
	return profileService
}

func InitializeShardService() shard.ShardService {
	mysqlHandler := database.NewMysql()
	masterShardMysqlRepository := masterShard.NewMasterShardDao(mysqlHandler)
	shardService := shard.NewShardService(masterShardMysqlRepository)
	return shardService
}

func InitializeTransactionService() transaction.TransactionService {
	mysqlHandler := database.NewMysql()
	commonTransactionMysqlRepository := commonTransaction.NewCommonTransactionDao(mysqlHandler)
	masterTransactionMysqlRepository := masterTransaction.NewMasterTransactionDao(mysqlHandler)
	userTransactionMysqlRepository := userTransaction.NewUserTransactionDao(mysqlHandler)
	redisHandler := database.NewRedis()
	userTransactionRedisRepository := masterTransaction2.NewUserTransactionDao(redisHandler)
	transactionService := transaction.NewTransactionService(commonTransactionMysqlRepository, masterTransactionMysqlRepository, userTransactionMysqlRepository, userTransactionRedisRepository)
	return transactionService
}
