name: UserExchange
package: userExchange
comment: "ユーザー交換"

structure:
  UserId:
    name: user_id
    type: string
    nullable: false
    number: 1
    comment: "ユーザーID"
  MasterExchangeId:
    name: master_exchange_id
    type: int64
    nullable: false
    number: 2
    comment: "交換ID"
  ResetAt:
    name: reset_at
    type: time
    nullable: false
    number: 3
    comment: "リセット日時"
  CreatedAt:
    name: created_at
    type: time
    nullable: false
    number: 4
    comment: "作成日時"
  UpdatedAt:
    name: updated_at
    type: time
    nullable: false
    number: 5
    comment: "更新日時"
primary:
  - UserId,MasterExchangeId
unique:
  - UserId,MasterExchangeId
