// ヘルスチェック

// @generated by protoc-gen-es v1.10.0
// @generated from file health/adminHealth/admin_health.proto (package api.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { AdminHealthType } from "./admin_health_type_enum_pb.js";

/**
 * @generated from message api.game.AdminHealth
 */
export const AdminHealth = /*@__PURE__*/ proto3.makeMessageType(
  "api.game.AdminHealth",
  () => [
    { no: 1, name: "health_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "admin_health_type", kind: "enum", T: proto3.getEnumType(AdminHealthType) },
  ],
);

