// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0
// @generated from file health/adminHealth/admin_health_type_enum.proto (package api.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from enum api.game.AdminHealthType
 */
export declare enum AdminHealthType {
  /**
   * @generated from enum value: AdminNone = 0;
   */
  AdminNone = 0,

  /**
   * @generated from enum value: AdminSuccess = 1;
   */
  AdminSuccess = 1,
}

