// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0
// @generated from file health/adminHealth/admin_health_type_enum.proto (package api.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum api.game.AdminHealthType
 */
export const AdminHealthType = /*@__PURE__*/ proto3.makeEnum(
  "api.game.AdminHealthType",
  [
    {no: 0, name: "AdminNone"},
    {no: 1, name: "AdminSuccess"},
  ],
);

