// Code generated by MockGen. DO NOT EDIT.
// Source: ./common_transaction_redis_repository.gen.go

// Package commonTransaction is a generated GoMock package.
package commonTransaction

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	redis "github.com/redis/go-redis/v9"
)

// MockCommonTransactionRedisRepository is a mock of CommonTransactionRedisRepository interface.
type MockCommonTransactionRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommonTransactionRedisRepositoryMockRecorder
}

// MockCommonTransactionRedisRepositoryMockRecorder is the mock recorder for MockCommonTransactionRedisRepository.
type MockCommonTransactionRedisRepositoryMockRecorder struct {
	mock *MockCommonTransactionRedisRepository
}

// NewMockCommonTransactionRedisRepository creates a new mock instance.
func NewMockCommonTransactionRedisRepository(ctrl *gomock.Controller) *MockCommonTransactionRedisRepository {
	mock := &MockCommonTransactionRedisRepository{ctrl: ctrl}
	mock.recorder = &MockCommonTransactionRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonTransactionRedisRepository) EXPECT() *MockCommonTransactionRedisRepositoryMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockCommonTransactionRedisRepository) Begin() redis.Pipeliner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(redis.Pipeliner)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockCommonTransactionRedisRepositoryMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockCommonTransactionRedisRepository)(nil).Begin))
}

// Commit mocks base method.
func (m *MockCommonTransactionRedisRepository) Commit(ctx context.Context, tx redis.Pipeliner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockCommonTransactionRedisRepositoryMockRecorder) Commit(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockCommonTransactionRedisRepository)(nil).Commit), ctx, tx)
}

// Rollback mocks base method.
func (m *MockCommonTransactionRedisRepository) Rollback(tx redis.Pipeliner) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Rollback", tx)
}

// Rollback indicates an expected call of Rollback.
func (mr *MockCommonTransactionRedisRepositoryMockRecorder) Rollback(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockCommonTransactionRedisRepository)(nil).Rollback), tx)
}
