// ヘルスチェック

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file health/commonHealth/common_health.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { CommonHealthEnum } from "./common_health_enum_pb.js";

/**
 * @generated from message api.admin.CommonHealth
 */
export class CommonHealth extends Message<CommonHealth> {
  /**
   * @generated from field: int64 health_id = 1;
   */
  healthId = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: api.admin.CommonHealthEnum common_health_enum = 3;
   */
  commonHealthEnum = CommonHealthEnum.CommonNone;

  constructor(data?: PartialMessage<CommonHealth>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.admin.CommonHealth";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "health_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    {
      no: 3,
      name: "common_health_enum",
      kind: "enum",
      T: proto3.getEnumType(CommonHealthEnum),
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): CommonHealth {
    return new CommonHealth().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): CommonHealth {
    return new CommonHealth().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): CommonHealth {
    return new CommonHealth().fromJsonString(jsonString, options);
  }

  static equals(
    a: CommonHealth | PlainMessage<CommonHealth> | undefined,
    b: CommonHealth | PlainMessage<CommonHealth> | undefined
  ): boolean {
    return proto3.util.equals(CommonHealth, a, b);
  }
}
