// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file health/commonHealth/common_health_enum.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum api.admin.CommonHealthEnum
 */
export enum CommonHealthEnum {
  /**
   * @generated from enum value: CommonNone = 0;
   */
  CommonNone = 0,

  /**
   * @generated from enum value: CommonSuccess = 1;
   */
  CommonSuccess = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(CommonHealthEnum)
proto3.util.setEnumType(CommonHealthEnum, "api.admin.CommonHealthEnum", [
  { no: 0, name: "CommonNone" },
  { no: 1, name: "CommonSuccess" },
]);
