// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: health/commonHealth/common_health_type_enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Game {

  /// <summary>Holder for reflection information generated from health/commonHealth/common_health_type_enum.proto</summary>
  public static partial class CommonHealthTypeEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for health/commonHealth/common_health_type_enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonHealthTypeEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFoZWFsdGgvY29tbW9uSGVhbHRoL2NvbW1vbl9oZWFsdGhfdHlwZV9lbnVt",
            "LnByb3RvEghhcGkuZ2FtZSo1ChBDb21tb25IZWFsdGhUeXBlEg4KCkNvbW1v",
            "bk5vbmUQABIRCg1Db21tb25TdWNjZXNzEAFCuwEKDGNvbS5hcGkuZ2FtZUIZ",
            "Q29tbW9uSGVhbHRoVHlwZUVudW1Qcm90b1ABWk9naXRodWIuY29tL2dhbWUt",
            "Y29yZS9nYy1zZXJ2ZXIvYXBpL2dhbWUvcHJlc2VudGF0aW9uL3NlcnZlci9o",
            "ZWFsdGgvY29tbW9uSGVhbHRoogIDQUdYqgIIQXBpLkdhbWXKAghBcGlcR2Ft",
            "ZeICFEFwaVxHYW1lXEdQQk1ldGFkYXRh6gIJQXBpOjpHYW1lYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Api.Game.CommonHealthType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CommonHealthType {
    [pbr::OriginalName("CommonNone")] CommonNone = 0,
    [pbr::OriginalName("CommonSuccess")] CommonSuccess = 1,
  }

  #endregion

}

#endregion Designer generated code
