// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: exchange/exchange_receive_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Game {

  /// <summary>Holder for reflection information generated from exchange/exchange_receive_response.proto</summary>
  public static partial class ExchangeReceiveResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for exchange/exchange_receive_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExchangeReceiveResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihleGNoYW5nZS9leGNoYW5nZV9yZWNlaXZlX3Jlc3BvbnNlLnByb3RvEghh",
            "cGkuZ2FtZRopZXhjaGFuZ2UvdXNlckV4Y2hhbmdlL3VzZXJfZXhjaGFuZ2Uu",
            "cHJvdG8aMmV4Y2hhbmdlL3VzZXJFeGNoYW5nZUl0ZW0vdXNlcl9leGNoYW5n",
            "ZV9pdGVtLnByb3RvItMBChdFeGNoYW5nZVJlY2VpdmVSZXNwb25zZRJACg11",
            "c2VyX2V4Y2hhbmdlGAEgASgLMhYuYXBpLmdhbWUuVXNlckV4Y2hhbmdlSABS",
            "DHVzZXJFeGNoYW5nZYgBARJNChJ1c2VyX2V4Y2hhbmdlX2l0ZW0YAiABKAsy",
            "Gi5hcGkuZ2FtZS5Vc2VyRXhjaGFuZ2VJdGVtSAFSEHVzZXJFeGNoYW5nZUl0",
            "ZW2IAQFCEAoOX3VzZXJfZXhjaGFuZ2VCFQoTX3VzZXJfZXhjaGFuZ2VfaXRl",
            "bUKyAQoMY29tLmFwaS5nYW1lQhxFeGNoYW5nZVJlY2VpdmVSZXNwb25zZVBy",
            "b3RvUAFaQ2dpdGh1Yi5jb20vZ2FtZS1jb3JlL2djLXNlcnZlci9hcGkvZ2Ft",
            "ZS9wcmVzZW50YXRpb24vcHJvdG8vZXhjaGFuZ2WiAgNBR1iqAghBcGkuR2Ft",
            "ZcoCCEFwaVxHYW1l4gIUQXBpXEdhbWVcR1BCTWV0YWRhdGHqAglBcGk6Okdh",
            "bWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Api.Game.UserExchangeReflection.Descriptor, global::Api.Game.UserExchangeItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Game.ExchangeReceiveResponse), global::Api.Game.ExchangeReceiveResponse.Parser, new[]{ "UserExchange", "UserExchangeItem" }, new[]{ "UserExchange", "UserExchangeItem" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExchangeReceiveResponse : pb::IMessage<ExchangeReceiveResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExchangeReceiveResponse> _parser = new pb::MessageParser<ExchangeReceiveResponse>(() => new ExchangeReceiveResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExchangeReceiveResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Game.ExchangeReceiveResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeReceiveResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeReceiveResponse(ExchangeReceiveResponse other) : this() {
      userExchange_ = other.userExchange_ != null ? other.userExchange_.Clone() : null;
      userExchangeItem_ = other.userExchangeItem_ != null ? other.userExchangeItem_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExchangeReceiveResponse Clone() {
      return new ExchangeReceiveResponse(this);
    }

    /// <summary>Field number for the "user_exchange" field.</summary>
    public const int UserExchangeFieldNumber = 1;
    private global::Api.Game.UserExchange userExchange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Game.UserExchange UserExchange {
      get { return userExchange_; }
      set {
        userExchange_ = value;
      }
    }

    /// <summary>Field number for the "user_exchange_item" field.</summary>
    public const int UserExchangeItemFieldNumber = 2;
    private global::Api.Game.UserExchangeItem userExchangeItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Game.UserExchangeItem UserExchangeItem {
      get { return userExchangeItem_; }
      set {
        userExchangeItem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExchangeReceiveResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExchangeReceiveResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserExchange, other.UserExchange)) return false;
      if (!object.Equals(UserExchangeItem, other.UserExchangeItem)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (userExchange_ != null) hash ^= UserExchange.GetHashCode();
      if (userExchangeItem_ != null) hash ^= UserExchangeItem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (userExchange_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserExchange);
      }
      if (userExchangeItem_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserExchangeItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (userExchange_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserExchange);
      }
      if (userExchangeItem_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserExchangeItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (userExchange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserExchange);
      }
      if (userExchangeItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserExchangeItem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExchangeReceiveResponse other) {
      if (other == null) {
        return;
      }
      if (other.userExchange_ != null) {
        if (userExchange_ == null) {
          UserExchange = new global::Api.Game.UserExchange();
        }
        UserExchange.MergeFrom(other.UserExchange);
      }
      if (other.userExchangeItem_ != null) {
        if (userExchangeItem_ == null) {
          UserExchangeItem = new global::Api.Game.UserExchangeItem();
        }
        UserExchangeItem.MergeFrom(other.UserExchangeItem);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (userExchange_ == null) {
              UserExchange = new global::Api.Game.UserExchange();
            }
            input.ReadMessage(UserExchange);
            break;
          }
          case 18: {
            if (userExchangeItem_ == null) {
              UserExchangeItem = new global::Api.Game.UserExchangeItem();
            }
            input.ReadMessage(UserExchangeItem);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (userExchange_ == null) {
              UserExchange = new global::Api.Game.UserExchange();
            }
            input.ReadMessage(UserExchange);
            break;
          }
          case 18: {
            if (userExchangeItem_ == null) {
              UserExchangeItem = new global::Api.Game.UserExchangeItem();
            }
            input.ReadMessage(UserExchangeItem);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
