// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: exchange/exchange_handler.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Game {

  /// <summary>Holder for reflection information generated from exchange/exchange_handler.proto</summary>
  public static partial class ExchangeHandlerReflection {

    #region Descriptor
    /// <summary>File descriptor for exchange/exchange_handler.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExchangeHandlerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9leGNoYW5nZS9leGNoYW5nZV9oYW5kbGVyLnByb3RvEghhcGkuZ2FtZRom",
            "ZXhjaGFuZ2UvZXhjaGFuZ2VfdXBkYXRlX3JlcXVlc3QucHJvdG8aJ2V4Y2hh",
            "bmdlL2V4Y2hhbmdlX3VwZGF0ZV9yZXNwb25zZS5wcm90bxonZXhjaGFuZ2Uv",
            "ZXhjaGFuZ2VfcmVjZWl2ZV9yZXF1ZXN0LnByb3RvGihleGNoYW5nZS9leGNo",
            "YW5nZV9yZWNlaXZlX3Jlc3BvbnNlLnByb3RvMqcBCghFeGNoYW5nZRJLCgZV",
            "cGRhdGUSHy5hcGkuZ2FtZS5FeGNoYW5nZVVwZGF0ZVJlcXVlc3QaIC5hcGku",
            "Z2FtZS5FeGNoYW5nZVVwZGF0ZVJlc3BvbnNlEk4KB1JlY2VpdmUSIC5hcGku",
            "Z2FtZS5FeGNoYW5nZVJlY2VpdmVSZXF1ZXN0GiEuYXBpLmdhbWUuRXhjaGFu",
            "Z2VSZWNlaXZlUmVzcG9uc2VCqgEKDGNvbS5hcGkuZ2FtZUIURXhjaGFuZ2VI",
            "YW5kbGVyUHJvdG9QAVpDZ2l0aHViLmNvbS9nYW1lLWNvcmUvZ2Mtc2VydmVy",
            "L2FwaS9nYW1lL3ByZXNlbnRhdGlvbi9wcm90by9leGNoYW5nZaICA0FHWKoC",
            "CEFwaS5HYW1lygIIQXBpXEdhbWXiAhRBcGlcR2FtZVxHUEJNZXRhZGF0YeoC",
            "CUFwaTo6R2FtZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Api.Game.ExchangeUpdateRequestReflection.Descriptor, global::Api.Game.ExchangeUpdateResponseReflection.Descriptor, global::Api.Game.ExchangeReceiveRequestReflection.Descriptor, global::Api.Game.ExchangeReceiveResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
