// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: health/health_handler.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Game {

  /// <summary>Holder for reflection information generated from health/health_handler.proto</summary>
  public static partial class HealthHandlerReflection {

    #region Descriptor
    /// <summary>File descriptor for health/health_handler.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HealthHandlerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtoZWFsdGgvaGVhbHRoX2hhbmRsZXIucHJvdG8SCGFwaS5nYW1lGiFoZWFs",
            "dGgvaGVhbHRoX2NoZWNrX3JlcXVlc3QucHJvdG8aImhlYWx0aC9oZWFsdGhf",
            "Y2hlY2tfcmVzcG9uc2UucHJvdG8yTgoGSGVhbHRoEkQKBUNoZWNrEhwuYXBp",
            "LmdhbWUuSGVhbHRoQ2hlY2tSZXF1ZXN0Gh0uYXBpLmdhbWUuSGVhbHRoQ2hl",
            "Y2tSZXNwb25zZUKpAQoMY29tLmFwaS5nYW1lQhJIZWFsdGhIYW5kbGVyUHJv",
            "dG9QAVpEZ2l0aHViLmNvbS9nYW1lLWNvcmUvZ2FtZS1zZXJ2ZXIvYXBpL2dh",
            "bWUvcHJlc2VudGF0aW9uL3NlcnZlci9oZWFsdGiiAgNBR1iqAghBcGkuR2Ft",
            "ZcoCCEFwaVxHYW1l4gIUQXBpXEdhbWVcR1BCTWV0YWRhdGHqAglBcGk6Okdh",
            "bWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Api.Game.HealthCheckRequestReflection.Descriptor, global::Api.Game.HealthCheckResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
