// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: health/health_check_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Game {

  /// <summary>Holder for reflection information generated from health/health_check_response.proto</summary>
  public static partial class HealthCheckResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for health/health_check_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HealthCheckResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJoZWFsdGgvaGVhbHRoX2NoZWNrX3Jlc3BvbnNlLnByb3RvEghhcGkuZ2Ft",
            "ZRonaGVhbHRoL2NvbW1vbkhlYWx0aC9jb21tb25faGVhbHRoLnByb3RvGido",
            "ZWFsdGgvbWFzdGVySGVhbHRoL21hc3Rlcl9oZWFsdGgucHJvdG8ivQEKE0hl",
            "YWx0aENoZWNrUmVzcG9uc2USQAoNY29tbW9uX2hlYWx0aBgBIAEoCzIWLmFw",
            "aS5nYW1lLkNvbW1vbkhlYWx0aEgAUgxjb21tb25IZWFsdGiIAQESQAoNbWFz",
            "dGVyX2hlYWx0aBgCIAEoCzIWLmFwaS5nYW1lLk1hc3RlckhlYWx0aEgBUgxt",
            "YXN0ZXJIZWFsdGiIAQFCEAoOX2NvbW1vbl9oZWFsdGhCEAoOX21hc3Rlcl9o",
            "ZWFsdGhCrAEKDGNvbS5hcGkuZ2FtZUIYSGVhbHRoQ2hlY2tSZXNwb25zZVBy",
            "b3RvUAFaQWdpdGh1Yi5jb20vZ2FtZS1jb3JlL2djLXNlcnZlci9hcGkvZ2Ft",
            "ZS9wcmVzZW50YXRpb24vcHJvdG8vaGVhbHRoogIDQUdYqgIIQXBpLkdhbWXK",
            "AghBcGlcR2FtZeICFEFwaVxHYW1lXEdQQk1ldGFkYXRh6gIJQXBpOjpHYW1l",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Api.Game.CommonHealthReflection.Descriptor, global::Api.Game.MasterHealthReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Game.HealthCheckResponse), global::Api.Game.HealthCheckResponse.Parser, new[]{ "CommonHealth", "MasterHealth" }, new[]{ "CommonHealth", "MasterHealth" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HealthCheckResponse : pb::IMessage<HealthCheckResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HealthCheckResponse> _parser = new pb::MessageParser<HealthCheckResponse>(() => new HealthCheckResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HealthCheckResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Game.HealthCheckResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthCheckResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthCheckResponse(HealthCheckResponse other) : this() {
      commonHealth_ = other.commonHealth_ != null ? other.commonHealth_.Clone() : null;
      masterHealth_ = other.masterHealth_ != null ? other.masterHealth_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthCheckResponse Clone() {
      return new HealthCheckResponse(this);
    }

    /// <summary>Field number for the "common_health" field.</summary>
    public const int CommonHealthFieldNumber = 1;
    private global::Api.Game.CommonHealth commonHealth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Game.CommonHealth CommonHealth {
      get { return commonHealth_; }
      set {
        commonHealth_ = value;
      }
    }

    /// <summary>Field number for the "master_health" field.</summary>
    public const int MasterHealthFieldNumber = 2;
    private global::Api.Game.MasterHealth masterHealth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.Game.MasterHealth MasterHealth {
      get { return masterHealth_; }
      set {
        masterHealth_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HealthCheckResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HealthCheckResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CommonHealth, other.CommonHealth)) return false;
      if (!object.Equals(MasterHealth, other.MasterHealth)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (commonHealth_ != null) hash ^= CommonHealth.GetHashCode();
      if (masterHealth_ != null) hash ^= MasterHealth.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (commonHealth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CommonHealth);
      }
      if (masterHealth_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MasterHealth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (commonHealth_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CommonHealth);
      }
      if (masterHealth_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MasterHealth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (commonHealth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CommonHealth);
      }
      if (masterHealth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MasterHealth);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HealthCheckResponse other) {
      if (other == null) {
        return;
      }
      if (other.commonHealth_ != null) {
        if (commonHealth_ == null) {
          CommonHealth = new global::Api.Game.CommonHealth();
        }
        CommonHealth.MergeFrom(other.CommonHealth);
      }
      if (other.masterHealth_ != null) {
        if (masterHealth_ == null) {
          MasterHealth = new global::Api.Game.MasterHealth();
        }
        MasterHealth.MergeFrom(other.MasterHealth);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (commonHealth_ == null) {
              CommonHealth = new global::Api.Game.CommonHealth();
            }
            input.ReadMessage(CommonHealth);
            break;
          }
          case 18: {
            if (masterHealth_ == null) {
              MasterHealth = new global::Api.Game.MasterHealth();
            }
            input.ReadMessage(MasterHealth);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (commonHealth_ == null) {
              CommonHealth = new global::Api.Game.CommonHealth();
            }
            input.ReadMessage(CommonHealth);
            break;
          }
          case 18: {
            if (masterHealth_ == null) {
              MasterHealth = new global::Api.Game.MasterHealth();
            }
            input.ReadMessage(MasterHealth);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
