// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: exchange/masterExchangeItem/master_exchange_item.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Game {

  /// <summary>Holder for reflection information generated from exchange/masterExchangeItem/master_exchange_item.proto</summary>
  public static partial class MasterExchangeItemReflection {

    #region Descriptor
    /// <summary>File descriptor for exchange/masterExchangeItem/master_exchange_item.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MasterExchangeItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjZleGNoYW5nZS9tYXN0ZXJFeGNoYW5nZUl0ZW0vbWFzdGVyX2V4Y2hhbmdl",
            "X2l0ZW0ucHJvdG8SCGFwaS5nYW1lIskBChJNYXN0ZXJFeGNoYW5nZUl0ZW0S",
            "NQoXbWFzdGVyX2V4Y2hhbmdlX2l0ZW1faWQYASABKANSFG1hc3RlckV4Y2hh",
            "bmdlSXRlbUlkEiwKEm1hc3Rlcl9leGNoYW5nZV9pZBgCIAEoA1IQbWFzdGVy",
            "RXhjaGFuZ2VJZBIkCg5tYXN0ZXJfaXRlbV9pZBgDIAEoA1IMbWFzdGVySXRl",
            "bUlkEhIKBG5hbWUYBCABKAlSBG5hbWUSFAoFY291bnQYBSABKAVSBWNvdW50",
            "QsABCgxjb20uYXBpLmdhbWVCF01hc3RlckV4Y2hhbmdlSXRlbVByb3RvUAFa",
            "VmdpdGh1Yi5jb20vZ2FtZS1jb3JlL2djLXNlcnZlci9hcGkvZ2FtZS9wcmVz",
            "ZW50YXRpb24vcHJvdG8vZXhjaGFuZ2UvbWFzdGVyRXhjaGFuZ2VJdGVtogID",
            "QUdYqgIIQXBpLkdhbWXKAghBcGlcR2FtZeICFEFwaVxHYW1lXEdQQk1ldGFk",
            "YXRh6gIJQXBpOjpHYW1lYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.Game.MasterExchangeItem), global::Api.Game.MasterExchangeItem.Parser, new[]{ "MasterExchangeItemId", "MasterExchangeId", "MasterItemId", "Name", "Count" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MasterExchangeItem : pb::IMessage<MasterExchangeItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MasterExchangeItem> _parser = new pb::MessageParser<MasterExchangeItem>(() => new MasterExchangeItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MasterExchangeItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.Game.MasterExchangeItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterExchangeItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterExchangeItem(MasterExchangeItem other) : this() {
      masterExchangeItemId_ = other.masterExchangeItemId_;
      masterExchangeId_ = other.masterExchangeId_;
      masterItemId_ = other.masterItemId_;
      name_ = other.name_;
      count_ = other.count_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterExchangeItem Clone() {
      return new MasterExchangeItem(this);
    }

    /// <summary>Field number for the "master_exchange_item_id" field.</summary>
    public const int MasterExchangeItemIdFieldNumber = 1;
    private long masterExchangeItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MasterExchangeItemId {
      get { return masterExchangeItemId_; }
      set {
        masterExchangeItemId_ = value;
      }
    }

    /// <summary>Field number for the "master_exchange_id" field.</summary>
    public const int MasterExchangeIdFieldNumber = 2;
    private long masterExchangeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MasterExchangeId {
      get { return masterExchangeId_; }
      set {
        masterExchangeId_ = value;
      }
    }

    /// <summary>Field number for the "master_item_id" field.</summary>
    public const int MasterItemIdFieldNumber = 3;
    private long masterItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MasterItemId {
      get { return masterItemId_; }
      set {
        masterItemId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 5;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MasterExchangeItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MasterExchangeItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MasterExchangeItemId != other.MasterExchangeItemId) return false;
      if (MasterExchangeId != other.MasterExchangeId) return false;
      if (MasterItemId != other.MasterItemId) return false;
      if (Name != other.Name) return false;
      if (Count != other.Count) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MasterExchangeItemId != 0L) hash ^= MasterExchangeItemId.GetHashCode();
      if (MasterExchangeId != 0L) hash ^= MasterExchangeId.GetHashCode();
      if (MasterItemId != 0L) hash ^= MasterItemId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MasterExchangeItemId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MasterExchangeItemId);
      }
      if (MasterExchangeId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MasterExchangeId);
      }
      if (MasterItemId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MasterItemId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (Count != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MasterExchangeItemId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MasterExchangeItemId);
      }
      if (MasterExchangeId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MasterExchangeId);
      }
      if (MasterItemId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MasterItemId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (Count != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MasterExchangeItemId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MasterExchangeItemId);
      }
      if (MasterExchangeId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MasterExchangeId);
      }
      if (MasterItemId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MasterItemId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MasterExchangeItem other) {
      if (other == null) {
        return;
      }
      if (other.MasterExchangeItemId != 0L) {
        MasterExchangeItemId = other.MasterExchangeItemId;
      }
      if (other.MasterExchangeId != 0L) {
        MasterExchangeId = other.MasterExchangeId;
      }
      if (other.MasterItemId != 0L) {
        MasterItemId = other.MasterItemId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MasterExchangeItemId = input.ReadInt64();
            break;
          }
          case 16: {
            MasterExchangeId = input.ReadInt64();
            break;
          }
          case 24: {
            MasterItemId = input.ReadInt64();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            Count = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MasterExchangeItemId = input.ReadInt64();
            break;
          }
          case 16: {
            MasterExchangeId = input.ReadInt64();
            break;
          }
          case 24: {
            MasterItemId = input.ReadInt64();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 40: {
            Count = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
