// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: health/masterHealth/master_health_enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api.Game {

  /// <summary>Holder for reflection information generated from health/masterHealth/master_health_enum.proto</summary>
  public static partial class MasterHealthEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for health/masterHealth/master_health_enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MasterHealthEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixoZWFsdGgvbWFzdGVySGVhbHRoL21hc3Rlcl9oZWFsdGhfZW51bS5wcm90",
            "bxIIYXBpLmdhbWUqNQoQTWFzdGVySGVhbHRoRW51bRIOCgpNYXN0ZXJOb25l",
            "EAASEQoNTWFzdGVyU3VjY2VzcxABQrYBCgxjb20uYXBpLmdhbWVCFU1hc3Rl",
            "ckhlYWx0aEVudW1Qcm90b1ABWk5naXRodWIuY29tL2dhbWUtY29yZS9nYy1z",
            "ZXJ2ZXIvYXBpL2dhbWUvcHJlc2VudGF0aW9uL3Byb3RvL2hlYWx0aC9tYXN0",
            "ZXJIZWFsdGiiAgNBR1iqAghBcGkuR2FtZcoCCEFwaVxHYW1l4gIUQXBpXEdh",
            "bWVcR1BCTWV0YWRhdGHqAglBcGk6OkdhbWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Api.Game.MasterHealthEnum), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MasterHealthEnum {
    [pbr::OriginalName("MasterNone")] MasterNone = 0,
    [pbr::OriginalName("MasterSuccess")] MasterSuccess = 1,
  }

  #endregion

}

#endregion Designer generated code
