name: MasterActionRun
package: masterActionRun
comment: "実行されるアクション"

structure:
  MasterActionRunId:
    name: master_action_run_id
    type: int64
    nullable: false
    number: 1
    comment: "実行されるアクションID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "実行されるアクション名"
  MasterActionId:
    name: master_action_id
    type: int64
    nullable: false
    number: 3
    comment: "アクションID"
primary:
  - MasterActionRunId
unique:
  - MasterActionRunId
index:
  - MasterActionId
