// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0
// @generated from file health/masterHealth/master_health_type_enum.proto (package api.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from enum api.game.MasterHealthType
 */
export declare enum MasterHealthType {
  /**
   * @generated from enum value: MasterNone = 0;
   */
  MasterNone = 0,

  /**
   * @generated from enum value: MasterSuccess = 1;
   */
  MasterSuccess = 1,
}

