// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0
// @generated from file health/masterHealth/master_health_type_enum.proto (package api.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum api.game.MasterHealthType
 */
export const MasterHealthType = /*@__PURE__*/ proto3.makeEnum(
  "api.game.MasterHealthType",
  [
    {no: 0, name: "MasterNone"},
    {no: 1, name: "MasterSuccess"},
  ],
);

