version: '3.8'

name: gc-server-web

volumes:
  node_modules:
    driver: local

services:
  web:
    container_name: gc-server-web
    env_file:
      - .env.local
    build:
      target: prod
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/web:cached
      - node_modules:/web/node_modules
    ports:
      - "3000:3000"
    tty: true
