// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0
// @generated from file health/commonHealth/common_health_type_enum.proto (package api.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from enum api.game.CommonHealthType
 */
export declare enum CommonHealthType {
  /**
   * @generated from enum value: CommonNone = 0;
   */
  CommonNone = 0,

  /**
   * @generated from enum value: CommonSuccess = 1;
   */
  CommonSuccess = 1,
}

