// ヘルスチェックタイプ

// @generated by protoc-gen-es v1.10.0
// @generated from file health/commonHealth/common_health_type_enum.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum api.admin.CommonHealthType
 */
export const CommonHealthType = /*@__PURE__*/ proto3.makeEnum(
  "api.admin.CommonHealthType",
  [
    {no: 0, name: "CommonNone"},
    {no: 1, name: "CommonSuccess"},
  ],
);

