// Code generated by MockGen. DO NOT EDIT.
// Source: ./user_item_box_mysql_repository.gen.go

// Package userItemBox is a generated GoMock package.
package userItemBox

import (
	context "context"
	reflect "reflect"
	time "time"

	logger "github.com/game-core/gc-server/config/logger"
	gomock "github.com/golang/mock/gomock"
)

// MockUserItemBoxCloudWatchRepository is a mock of UserItemBoxCloudWatchRepository interface.
type MockUserItemBoxCloudWatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserItemBoxCloudWatchRepositoryMockRecorder
}

// MockUserItemBoxCloudWatchRepositoryMockRecorder is the mock recorder for MockUserItemBoxCloudWatchRepository.
type MockUserItemBoxCloudWatchRepositoryMockRecorder struct {
	mock *MockUserItemBoxCloudWatchRepository
}

// NewMockUserItemBoxCloudWatchRepository creates a new mock instance.
func NewMockUserItemBoxCloudWatchRepository(ctrl *gomock.Controller) *MockUserItemBoxCloudWatchRepository {
	mock := &MockUserItemBoxCloudWatchRepository{ctrl: ctrl}
	mock.recorder = &MockUserItemBoxCloudWatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserItemBoxCloudWatchRepository) EXPECT() *MockUserItemBoxCloudWatchRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockUserItemBoxCloudWatchRepository) Create(ctx context.Context, now time.Time, level logger.LogLevel, m *UserItemBox) {
	m_2.ctrl.T.Helper()
	m_2.ctrl.Call(m_2, "Create", ctx, now, level, m)
}

// Create indicates an expected call of Create.
func (mr *MockUserItemBoxCloudWatchRepositoryMockRecorder) Create(ctx, now, level, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserItemBoxCloudWatchRepository)(nil).Create), ctx, now, level, m)
}

// CreateList mocks base method.
func (m *MockUserItemBoxCloudWatchRepository) CreateList(ctx context.Context, now time.Time, level logger.LogLevel, ms UserItemBoxes) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateList", ctx, now, level, ms)
}

// CreateList indicates an expected call of CreateList.
func (mr *MockUserItemBoxCloudWatchRepositoryMockRecorder) CreateList(ctx, now, level, ms interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateList", reflect.TypeOf((*MockUserItemBoxCloudWatchRepository)(nil).CreateList), ctx, now, level, ms)
}
