// ヘルスチェック

// @generated by protoc-gen-connect-es v1.4.0
// @generated from file health/health_handler.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthCheckRequest } from "./health_check_request_pb.js";
import { HealthCheckResponse } from "./health_check_response_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.admin.Health
 */
export declare const Health: {
  readonly typeName: "api.admin.Health",
  readonly methods: {
    /**
     * @generated from rpc api.admin.Health.Check
     */
    readonly check: {
      readonly name: "Check",
      readonly I: typeof HealthCheckRequest,
      readonly O: typeof HealthCheckResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

