// ヘルスチェック

// @generated by protoc-gen-connect-es v1.4.0
// @generated from file health/health_handler.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthCheckRequest } from "./health_check_request_pb.js";
import { HealthCheckResponse } from "./health_check_response_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.admin.Health
 */
export const Health = {
  typeName: "api.admin.Health",
  methods: {
    /**
     * @generated from rpc api.admin.Health.Check
     */
    check: {
      name: "Check",
      I: HealthCheckRequest,
      O: HealthCheckResponse,
      kind: MethodKind.Unary,
    },
  }
};

