// ヘルスチェックリクエスト

// @generated by protoc-gen-es v1.10.0
// @generated from file health/health_check_request.proto (package api.game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message api.game.HealthCheckRequest
 */
export declare class HealthCheckRequest extends Message<HealthCheckRequest> {
  /**
   * @generated from field: int64 health_id = 1;
   */
  healthId: bigint;

  constructor(data?: PartialMessage<HealthCheckRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.game.HealthCheckRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HealthCheckRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HealthCheckRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HealthCheckRequest;

  static equals(a: HealthCheckRequest | PlainMessage<HealthCheckRequest> | undefined, b: HealthCheckRequest | PlainMessage<HealthCheckRequest> | undefined): boolean;
}

