// ヘルスチェックレスポンス

// @generated by protoc-gen-es v1.10.0
// @generated from file health/health_check_response.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { AdminHealth } from "./adminHealth/admin_health_pb.js";
import type { CommonHealth } from "./commonHealth/common_health_pb.js";
import type { MasterHealth } from "./masterHealth/master_health_pb.js";

/**
 * @generated from message api.admin.HealthCheckResponse
 */
export declare class HealthCheckResponse extends Message<HealthCheckResponse> {
  /**
   * @generated from field: optional api.admin.AdminHealth admin_health = 1;
   */
  adminHealth?: AdminHealth;

  /**
   * @generated from field: optional api.admin.CommonHealth common_health = 2;
   */
  commonHealth?: CommonHealth;

  /**
   * @generated from field: optional api.admin.MasterHealth master_health = 3;
   */
  masterHealth?: MasterHealth;

  constructor(data?: PartialMessage<HealthCheckResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "api.admin.HealthCheckResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HealthCheckResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HealthCheckResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HealthCheckResponse;

  static equals(a: HealthCheckResponse | PlainMessage<HealthCheckResponse> | undefined, b: HealthCheckResponse | PlainMessage<HealthCheckResponse> | undefined): boolean;
}

