name: MasterRarity
package: masterRarity
comment: "レアリティ"

structure:
  MasterRarityId:
    name: master_rarity_id
    type: int64
    nullable: false
    number: 1
    comment: "レアリティID"
  Name:
    name: name
    type: string
    nullable: false
    number: 2
    comment: "レアリティ名"
  MasterRarityEnum:
    name: master_rarity_enum
    type: enum
    package: rarity/masterRarity
    nullable: false
    number: 3
    comment: "レアリティEnum"
primary:
  - MasterRarityId
unique:
  - MasterRarityId
index:
  - MasterRarityEnum
