// 管理者アカウントのGoogleToken情報

// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file account/adminAccountGoogleTokenInfo/admin_account_google_token_info.proto (package api.admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message api.admin.AdminAccountGoogleTokenInfo
 */
export class AdminAccountGoogleTokenInfo extends Message<AdminAccountGoogleTokenInfo> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: bool verified_email = 3;
   */
  verifiedEmail = false;

  /**
   * @generated from field: int64 expires_in = 4;
   */
  expiresIn = protoInt64.zero;

  /**
   * @generated from field: string issued_to = 5;
   */
  issuedTo = "";

  /**
   * @generated from field: string scope = 6;
   */
  scope = "";

  constructor(data?: PartialMessage<AdminAccountGoogleTokenInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "api.admin.AdminAccountGoogleTokenInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    {
      no: 3,
      name: "verified_email",
      kind: "scalar",
      T: 8 /* ScalarType.BOOL */,
    },
    { no: 4, name: "expires_in", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "issued_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "scope", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): AdminAccountGoogleTokenInfo {
    return new AdminAccountGoogleTokenInfo().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): AdminAccountGoogleTokenInfo {
    return new AdminAccountGoogleTokenInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): AdminAccountGoogleTokenInfo {
    return new AdminAccountGoogleTokenInfo().fromJsonString(
      jsonString,
      options
    );
  }

  static equals(
    a:
      | AdminAccountGoogleTokenInfo
      | PlainMessage<AdminAccountGoogleTokenInfo>
      | undefined,
    b:
      | AdminAccountGoogleTokenInfo
      | PlainMessage<AdminAccountGoogleTokenInfo>
      | undefined
  ): boolean {
    return proto3.util.equals(AdminAccountGoogleTokenInfo, a, b);
  }
}
